apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-v2-autoscaller
#  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-v2 #nombre del target del scalado
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
